import type { EventFormData } from "./types"

export function getDefaultCreateEventFormData(): EventFormData {
  return {
    title: "",
    subTitle: "",
    slug: "",
    description: "",
    eventType: "CONFERENCE",
    categories: [],
    edition: 0,
    startDate: "",
    endDate: "",
    dailyStart: "10:00",
    dailyEnd: "18:00",
    timezone: "",
    venueId: "",
    venue: "",
    city: "",
    state: "",
    country: "",
    address: "",
    currency: "₹",
    generalPrice: 0,
    studentPrice: 0,
    vipPrice: 0,
    groupPrice: 0,
    highlights: [],
    tags: [],
    dressCode: "Business Casual",
    ageLimit: "18+",
    featured: false,
    vip: false,
    ticketTypes: [],
    spaceCosts: [
      {
        type: "Shell Space (Standard Booth)",
        hallName: "",
        description: "Fully constructed booth with walls, flooring, basic lighting, and standard amenities",
        pricePerSqm: 5000,
        minArea: 9,
        isFixed: true,
      },
      {
        type: "Raw Space",
        hallName: "",
        description: "Open floor space without any construction or amenities",
        pricePerSqm: 2500,
        minArea: 20,
        isFixed: true,
      },
    ],
    images: [],
    brochure: "",
    layoutPlan: "",
    featuredHotels: [],
    travelPartners: [],
    touristAttractions: [],
    ageRestriction: "",
    accessibility: "",
    parking: "",
    publicTransport: "",
    foodBeverage: "",
    wifi: "",
    photography: "",
    recording: "",
    liveStreaming: "",
    socialMedia: "",
    networking: "",
    certificates: "",
    materials: "",
    followUp: "",
  }
}
