/**
 * ISO-3166 alpha-2 country names and venue-string aliases for home location filtering.
 * Rich alias rows include major cities; every known code gets at least name + ISO code.
 */

/** Detailed aliases (country names, cities, codes) for high-traffic regions. */
export const RICH_COUNTRY_ALIASES: Record<string, string[]> = {
  IN: ["india", "in", "bharat"],

  AE: ["uae", "united arab emirates", "dubai", "abu dhabi", "sharjah", "ae"],
  SA: ["saudi arabia", "saudi", "riyadh", "jeddah", "sa"],
  QA: ["qatar", "doha", "qa"],
  KW: ["kuwait", "kw"],
  OM: ["oman", "muscat", "om"],
  BH: ["bahrain", "manama", "bh"],
  JO: ["jordan", "amman", "jo"],

  SG: ["singapore", "sg"],
  MY: ["malaysia", "kuala lumpur", "my"],
  TH: ["thailand", "bangkok", "th"],
  ID: ["indonesia", "jakarta", "id"],
  PH: ["philippines", "manila", "ph"],
  VN: ["vietnam", "viet nam", "hanoi", "ho chi minh city", "vn"],
  KR: ["south korea", "republic of korea", "korea", "seoul", "kr"],
  JP: ["japan", "tokyo", "osaka", "jp"],
  CN: [
    "china",
    "prc",
    "people's republic of china",
    "peoples republic of china",
    "chn",
    "beijing",
    "shanghai",
    "guangzhou",
    "cn",
  ],
  HK: ["hong kong", "hk"],
  TW: ["taiwan", "taipei", "tw"],
  MO: ["macau", "macao", "mo"],

  PK: ["pakistan", "karachi", "lahore", "islamabad", "pk"],
  BD: ["bangladesh", "dhaka", "bd"],
  LK: ["sri lanka", "colombo", "lk"],
  NP: ["nepal", "kathmandu", "np"],

  US: ["united states", "usa", "u.s.", "america", "new york", "las vegas", "chicago", "us"],
  CA: ["canada", "toronto", "vancouver", "montreal", "ca"],
  MX: ["mexico", "mexico city", "mx"],
  BR: ["brazil", "sao paulo", "rio de janeiro", "br"],
  AR: ["argentina", "buenos aires", "ar"],
  CL: ["chile", "santiago", "cl"],
  CO: ["colombia", "bogota", "co"],
  PE: ["peru", "lima", "pe"],

  GB: ["united kingdom", "uk", "britain", "england", "scotland", "wales", "london", "gb"],
  IE: ["ireland", "dublin", "ie"],
  FR: ["france", "paris", "fr"],
  DE: ["germany", "deutschland", "berlin", "frankfurt", "munich", "de"],
  NL: ["netherlands", "holland", "amsterdam", "rotterdam", "nl"],
  BE: ["belgium", "brussels", "be"],
  CH: ["switzerland", "zurich", "geneva", "ch"],
  AT: ["austria", "vienna", "at"],
  IT: ["italy", "milan", "rome", "it"],
  ES: ["spain", "madrid", "barcelona", "es"],
  PT: ["portugal", "lisbon", "pt"],
  GR: ["greece", "athens", "gr"],
  PL: ["poland", "warsaw", "pl"],
  CZ: ["czech republic", "czechia", "prague", "cz"],
  HU: ["hungary", "budapest", "hu"],
  RO: ["romania", "bucharest", "ro"],
  SE: ["sweden", "stockholm", "se"],
  NO: ["norway", "oslo", "no"],
  DK: ["denmark", "copenhagen", "dk"],
  FI: ["finland", "helsinki", "fi"],
  UA: ["ukraine", "kyiv", "kiev", "ua"],
  RU: ["russia", "moscow", "saint petersburg", "ru"],
  TR: ["turkey", "turkiye", "istanbul", "ankara", "tr"],

  AU: ["australia", "sydney", "melbourne", "brisbane", "au"],
  NZ: ["new zealand", "auckland", "wellington", "nz"],

  ZA: ["south africa", "johannesburg", "cape town", "za"],
  EG: ["egypt", "cairo", "eg"],
  NG: ["nigeria", "lagos", "abuja", "ng"],
  KE: ["kenya", "nairobi", "ke"],
  MA: ["morocco", "casablanca", "ma"],
  DZ: ["algeria", "algiers", "dz"],

  IL: ["israel", "tel aviv", "jerusalem", "il"],
}

/** ISO alpha-2 → English display name (all countries / territories commonly returned by geo APIs). */
export const COUNTRY_NAMES: Record<string, string> = {
  AF: "Afghanistan",
  AX: "Åland Islands",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua and Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BA: "Bosnia and Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  IO: "British Indian Ocean Territory",
  BN: "Brunei",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo",
  CD: "Democratic Republic of the Congo",
  CK: "Cook Islands",
  CR: "Costa Rica",
  CI: "Côte d'Ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CW: "Curaçao",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  SZ: "Eswatini",
  ET: "Ethiopia",
  FK: "Falkland Islands",
  FO: "Faroe Islands",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island and McDonald Islands",
  VA: "Holy See",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle of Man",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Laos",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macau",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  MK: "North Macedonia",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestine",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PN: "Pitcairn",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RU: "Russia",
  RW: "Rwanda",
  BL: "Saint Barthélemy",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  MF: "Saint Martin",
  PM: "Saint Pierre and Miquelon",
  VC: "Saint Vincent and the Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome and Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SX: "Sint Maarten",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  GS: "South Georgia and the South Sandwich Islands",
  SS: "South Sudan",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SJ: "Svalbard and Jan Mayen",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syria",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks and Caicos Islands",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UM: "United States Minor Outlying Islands",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Vietnam",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",
  WF: "Wallis and Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
}

function mergeCountryAliases(): Record<string, string[]> {
  const out: Record<string, string[]> = { ...RICH_COUNTRY_ALIASES }
  for (const [cc, name] of Object.entries(COUNTRY_NAMES)) {
    if (out[cc]) continue
    const lower = name.toLowerCase()
    const aliases = new Set<string>([lower, cc.toLowerCase()])
    if (lower.includes(",")) {
      aliases.add(lower.split(",")[0]!.trim())
    }
    out[cc] = [...aliases]
  }
  return out
}

/** Full alias map: rich rows + generated name/code for every ISO entry above. */
export const ISO_COUNTRY_ALIASES: Record<string, string[]> = mergeCountryAliases()

export function countryNameFromCode(code: string | null | undefined): string | null {
  if (!code?.trim()) return null
  const cc = code.trim().toUpperCase()
  return COUNTRY_NAMES[cc] ?? cc
}
